package com.test.testproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TestObject implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Description")
   private java.lang.String description;
   @org.kie.api.definition.type.Label("Owner Auth")
   private java.lang.Boolean ownerAuth;
   @org.kie.api.definition.type.Label("Executive Auth")
   private java.lang.Boolean executiveAuth;
   @org.kie.api.definition.type.Label("Result")
   private java.lang.Boolean result;

   @org.kie.api.definition.type.Label("Reject Comment")
   private java.lang.String rejectComment;

   @org.kie.api.definition.type.Label("date")
   private java.lang.String date;

   @org.kie.api.definition.type.Label("authElec")
   private Boolean authElec;

   @org.kie.api.definition.type.Label("authStruc")
   private boolean authStruc;

   public TestObject()
   {
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public java.lang.Boolean getOwnerAuth()
   {
      return this.ownerAuth;
   }

   public void setOwnerAuth(java.lang.Boolean ownerAuth)
   {
      this.ownerAuth = ownerAuth;
   }

   public java.lang.Boolean getExecutiveAuth()
   {
      return this.executiveAuth;
   }

   public void setExecutiveAuth(java.lang.Boolean executiveAuth)
   {
      this.executiveAuth = executiveAuth;
   }

   public java.lang.Boolean getResult()
   {
      return this.result;
   }

   public void setResult(java.lang.Boolean result)
   {
      this.result = result;
   }

   public java.lang.String getRejectComment()
   {
      return this.rejectComment;
   }

   public void setRejectComment(java.lang.String rejectComment)
   {
      this.rejectComment = rejectComment;
   }

   public java.lang.String getDate()
   {
      return this.date;
   }

   public void setDate(java.lang.String date)
   {
      this.date = date;
   }

   public boolean isAuthStruc()
   {
      return this.authStruc;
   }

   public void setAuthStruc(boolean authStruc)
   {
      this.authStruc = authStruc;
   }

   public java.lang.Boolean getAuthElec()
   {
      return this.authElec;
   }

   public void setAuthElec(java.lang.Boolean authElec)
   {
      this.authElec = authElec;
   }

   public TestObject(java.lang.String description, java.lang.Boolean ownerAuth,
         java.lang.Boolean executiveAuth, java.lang.Boolean result,
         java.lang.String rejectComment, java.lang.String date,
         java.lang.Boolean authElec, boolean authStruc)
   {
      this.description = description;
      this.ownerAuth = ownerAuth;
      this.executiveAuth = executiveAuth;
      this.result = result;
      this.rejectComment = rejectComment;
      this.date = date;
      this.authElec = authElec;
      this.authStruc = authStruc;
   }

}