package com.test.testproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TestObject implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Description")
   private java.lang.String description;
   @org.kie.api.definition.type.Label("Owner Auth")
   private java.lang.Boolean ownerAuth;
   @org.kie.api.definition.type.Label("Executive Auth")
   private java.lang.Boolean executiveAuth;
   @org.kie.api.definition.type.Label("Result")
   private java.lang.Boolean result;

   @org.kie.api.definition.type.Label(value = "Reject Comment")
   private java.lang.String rejectComment;

   public TestObject()
   {
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public java.lang.Boolean getOwnerAuth()
   {
      return this.ownerAuth;
   }

   public void setOwnerAuth(java.lang.Boolean ownerAuth)
   {
      this.ownerAuth = ownerAuth;
   }

   public java.lang.Boolean getExecutiveAuth()
   {
      return this.executiveAuth;
   }

   public void setExecutiveAuth(java.lang.Boolean executiveAuth)
   {
      this.executiveAuth = executiveAuth;
   }

   public java.lang.Boolean getResult()
   {
      return this.result;
   }

   public void setResult(java.lang.Boolean result)
   {
      this.result = result;
   }

   public java.lang.String getRejectComment()
   {
      return this.rejectComment;
   }

   public void setRejectComment(java.lang.String rejectComment)
   {
      this.rejectComment = rejectComment;
   }

   public TestObject(java.lang.String description, java.lang.Boolean ownerAuth,
         java.lang.Boolean executiveAuth, java.lang.Boolean result,
         java.lang.String rejectComment)
   {
      this.description = description;
      this.ownerAuth = ownerAuth;
      this.executiveAuth = executiveAuth;
      this.result = result;
      this.rejectComment = rejectComment;
   }

}